config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home#index'
  get 'home' => 'home#index'
  get 'about' => 'home#about'
  get 'video' => 'home#video'
  get 'blog' => 'home#blog'
  get 'photo' => 'home#photo'
  get '/video/:id' =>  'video#show', as: :openvideo

end

app/models/about.rb
class About < ActiveRecord::Base
	has_attached_file :img, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :img, :content_type => /\Aimage\/.*\Z/
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :img, :styles => { :medium => "500>x", :thumb => "40x40" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :img, :content_type => /\Aimage\/.*\Z/
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	has_attached_file :img, :styles => { :medium => "600>x", :thumb => "40x40" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :img, :content_type => /\Aimage\/.*\Z/
end

app/models/url.rb
class Url < ActiveRecord::Base
end

app/models/video.rb
class Video < ActiveRecord::Base
	before_update :all_index_to_nil

	def all_index_to_nil
		Video.update_all(to_index:false) if to_index
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	  before_action :load_categories

	def index
		@video = Video.where(to_index: true).first
	end

	def video
		require 'net/http'

		@videos = Video.all.order(created_at: :desc).order(order: :asc)
		@videos.each do |video|
			if video.img_url.empty?
				source = "http://vimeo.com/api/v2/video/#{video.vimeoid}.json"
				data = Net::HTTP.get_response(URI.parse(source)).body
				result = JSON.parse(data)
				video.update(img_url: result[0]['thumbnail_large'])
			end
		end
		@home_video_id = Video.where(to_index:true).first.vimeoid
	end

	def about
		@about = About.last
	end

	def blog
			@blogs = Blog.all.order(created_at: :desc)
	end	

	def photo
		images = Photo.all.order(order: :desc,created_at: :desc,)
		@images_odd = []
		@images_even = []
		images.each_with_index do |photo, index|
			(index.even? ? @images_odd : @images_even) << { small: photo.img.url, large: photo.img.url(:medium) }
		end
	end

  private
	  def load_categories
		  @links = Url.all.order(order: :asc)
	  end

end

app/controllers/video_controller.rb
class VideoController < ApplicationController
	def show
		@id = Video.find(params[:id]).vimeoid
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/home/about.html.slim
.body
	.container
		.six.columns.about.about_img
			=image_tag @about.img, style:"float:right"
		.six.columns.about.about_body
			==@about.body
			

app/views/home/blog.html.slim
.container
	-@blogs.each do |blog|
		.row
			.blog_title
				==blog.title
			.blog_subtitle
				==blog.subtitle
			.blog_body
				==blog.body
		hr

app/views/home/index.html.slim
.container.videos.container_videos
  .row
    .body#home
    	iframe width="100%" height="506" frameborder="0" badge="false" src="//player.vimeo.com/video/#{@video.vimeoid}?portrait=0&amp;&amp;title=0&amp;byline=0&amp;badge=0&amp;color=ffffff"

.bottom
	.center style="width:50%;"
		p Copiright © Loveliness
			<br>
			2015

app/views/home/photo.html.slim
.container.images.container_images
  .row#links
    .six.columns
		  -@images_odd.each do |image|
		    = link_to(image_tag(image[:large]), image[:small]) if image
    .six.columns
    	-@images_even.each do |image|
		    = link_to(image_tag(image[:large]), image[:small]) if image
#blueimp-gallery.blueimp-gallery.blueimp-gallery-controls
	.slides
    h3.title
    a.prev ‹
    a.next ›
    a.close ×
    a.play-pause
    / ol.indicator
javascript:
	document.getElementById('links').onclick = function (event) {
    event = event || window.event;
    var target = event.target || event.srcElement,
        link = target.src ? target.parentNode : target,
        options = {index: link, event: event},
        links = this.getElementsByTagName('a');
    blueimp.Gallery(links, options);
	};

app/views/home/video.html.slim
.container.videos.container_videos
	.row
		#video style="display: block !important;"
			iframe width="100%" height="506" frameborder="0" src="//player.vimeo.com/video/#{@home_video_id}?portrait=0&amp;&amp;title=0&amp;byline=0&amp;badge=0&amp;color=ffffff"
.container.videos.container_videos
	.row
		-@videos.each do |video|
			.video_image_container
				=link_to openvideo_path(video), remote:true do
					=image_tag video.img_url, class:"video_image"

app/views/layouts/_header.html.slim
header#header.clearfix
	h1#title LOVELINESS
	ul#menu.clearfix
			-@links[0..-2].each do |link|
				li=link_to link.name, link.url, class:"#{'active' if request.path_info==link.url}"
			li.last= link_to(@links.last.name, @links.last.url, class:"#{'active' if request.path_info==@links.last.url}")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loveliness</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/video/show.js.erb
iframe = $('<iframe width="100%" height="506" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen />');
iframe.attr('src', "//player.vimeo.com/video/"+<%=@id%>+"?portrait=0&amp;&amp;title=0&amp;byline=0&amp;badge=0&amp;color=ffffff");
// $('div#video').html(iframe);
$('div#video').show().html(iframe).fadeIn(200);